name: Build Xvfb (x86_64 + ARM64)

on:
  push:
    tags:
      - "v*"           # Run when you push a tag like v1.0.0
  workflow_dispatch:   # Allow manual trigger

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - name: x86_64
            runner: ubuntu-latest
            arch: amd64
          - name: arm64
            runner: ubuntu-24.04-arm64
            arch: arm64

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y meson ninja-build pkg-config python3 python3-pip build-essential git x11-xkb-utils

      - name: Run Debian install script
        run: sudo bash .gitlab-ci/debian-install.sh

      - name: Build cross prereqs for i686-w64-mingw32
        run: sudo .gitlab-ci/cross-prereqs-build.sh i686-w64-mingw32

      - name: Meson setup (normal)
        run: meson setup build

      - name: Meson setup (static Xvfb)
        run: meson setup build -Dxorg=false -Dc_link_args="-static" -Ddefault_library=static --reconfigure

      - name: Compile project
        run: meson compile -C build

      - name: Show binary info
        run: |
          file build/hw/vfb/Xvfb || true
          ls -lh build/hw/vfb/Xvfb || true

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Xvfb-${{ matrix.arch }}
          path: build/hw/vfb/Xvfb

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/Xvfb-amd64/Xvfb
            artifacts/Xvfb-arm64/Xvfb
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
