name: Publish latest release

on:
  push:
    tags:
      - 'v*'   # runs on v1.0, v2.1.3, etc.
  workflow_dispatch:   # Manual trigger

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh jq git

      - name: Get latest tag
        id: tag
        run: |
          tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          if [ -z "$tag" ]; then
            echo "No tag found, creating one"
            tag="auto-$(date +%Y%m%d-%H%M%S)"
            git tag $tag
            git push origin $tag
          fi
          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "Using tag: $tag"

      - name: Get latest successful build run ID
        id: get_run
        run: |
          run_id=$(gh run list --workflow "Build Xvfb (x86_64 + ARM64)" --branch main --json databaseId,status,conclusion -q '.[] | select(.status=="completed" and .conclusion=="success") | .databaseId' | head -n1)
          if [ -z "$run_id" ]; then
            echo "No successful build found" && exit 1
          fi
          echo "Found build run ID: $run_id"
          echo "run_id=$run_id" >> $GITHUB_OUTPUT

      - name: Download artifacts
        run: |
          mkdir artifacts
          gh run download ${{ steps.get_run.outputs.run_id }} --dir artifacts
          ls -R artifacts

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          release_name: Release ${{ steps.tag.outputs.tag }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts to release
        run: |
          for file in $(find artifacts -type f); do
            echo "Uploading $file..."
            gh release upload "${{ steps.tag.outputs.tag }}" "$file" --clobber
          done